### PR TITLE
stack-config json schema

### PR DESCRIPTION
**Pull request by dylanbannon**
## what
Including a comprehensive stack config JSON schema.

## why
The goal is to provide infrastructure for linting of config files used by `atmos`.

### CODE REVIEW

**Comment by dylanbannon** [comment]
Testing fit of schema to existing `atmos` YAML files:
```
$ yajsv -s ./cloudposse-stack-config-schema.json
../../example/stacks/workflows.yaml: pass
../../example/stacks/ue2-globals.yaml: pass
../../example/stacks/ue2-prod.yaml: pass
../../example/stacks/ue2-dev.yaml: pass
../../example/stacks/ue2-staging.yaml: pass
../../example/stacks/globals.yaml: fail: components.terraform.vpc: vars is required
../../example/stacks/globals-2.yaml: pass
1 of 7 failed validation
../../example/stacks/globals.yaml: fail: components.terraform.vpc: vars is required
```

**Comment by dylanbannon** [comment]
In its current state, the schema validates all YAML files in `example/stacks` and all the files included in the `.tgz` file @osterman sent me.

**Review by aknysh — COMMENTED** [review]
LGTM
Do we need to name the file `cloudposse-stack-config-schema.json` ? with `cloudposse` in the name?
Maybe just `stack-config-schema.json`

**Review by aknysh — APPROVED** [review]

**Review by Gowiem — APPROVED** [review]

**Comment by osterman** [comment]
LGTM

**Pull request merged**
